### ISSUE TITLE
Format code ci/cd failed

### ISSUE THREAD

**Issue by alvinfebriando** [SEA-Compfest-12-X-AE-A-12/SEA-Store-backend#14]
CI/CD untuk format code failed

```bash
  /usr/bin/git push ***github.com/SEA-Compfest-12-X-AE-A-12/SEA-Store-backend.git
  remote: error: GH006: Protected branch update failed for refs/heads/testing.        
  remote: error: At least 2 approving reviews are required by reviewers with write access.   
```
Solusi:
1. buat workflow baru lagi, setiap yang dipush ke testing diformat pake google style trus di push ke formatted yang gk di protect trus setiap kita mau push kita pull dari formatted.
2. Jalankan formatter nya di local baru di push ke testing

**Comment by JoshEvan** [comment]
ohh mantapp, atau baru kepikiran, 
kalau diubah akan jalan setiap push, kecuali ke branch `master` dan `testing` gimanaa??

mungkin nanti jadinya kan kita push ke remote branch selain ` master` dan `testing` dulu (disini di format) baru nanti buat PR, kalau update2 disana (push ke branch PR nya itu (diformat disana)) baru di push ke `testing` waktu merge PR...

bisa ga ya kira2??

**Comment by alvinfebriando** [comment]
Ohh github action bisa exclude branch? Klo bisa gitu aja lebih gampang

**Comment by JoshEvan** [comment]
oke wkwkw, iya kayanya wkwkw,
okee coba kuubah ya wkwkwk
